---
# tasks file for deploy_ct

# Install dependencies
- name: Remove man-db
  apt:
    pkg: man-db
    state: absent
  become: true

- name: Install dependencies
  apt:
    pkg:
      - mariadb-server
      - git
      - golang-go
    update_cache: yes
  become: true

# Configure database backend
- name: Configure MySQL secure installation
  ansible.builtin.expect:
    command: sudo mysql_secure_installation
    responses:
      'Enter current password for root': '{{ root_password }}'
      'Switch to unix_socket authentication': '{{ unix_socket_authentication }}'
      'Change the root password': '{{ change_root_password }}'
      'New password:': '{{ trillian_db_password }}'
      'Re-enter new password:': '{{ trillian_db_password }}'
      'Remove anonymous users': '{{ remove_anonymous_users }}'
      'Disallow root login remotely': '{{ disallow_remote_root_login }}'
      'Remove test database and access to it': '{{ remove_test_db }}'
      'Reload privilege tables now': '{{ reload_privilege_tables }}'
    timeout: 5

- name: Replace placeholder database name in Trillian database creation script
  ansible.builtin.replace:
    path: /tmp/ctl/scripts/createdb.sh
    regexp: '^DB="test"$'
    replace: "DB={{ trillian_db_name }}"

- name: Replace placeholder database user in Trillian database creation script
  ansible.builtin.replace:
    path: /tmp/ctl/scripts/createdb.sh
    regexp: '^USER="test"$'
    replace: "USER={{ trillian_db_user }}"

- name: Replace placeholder database password in Trillian database creation script
  ansible.builtin.replace:
    path: /tmp/ctl/scripts/createdb.sh
    regexp: '^PASS="zaphod"$'
    replace: "PASS={{ trillian_db_password }}"
  no_log: true

- name: Replace placeholder database root password in Trillian database creation script
  ansible.builtin.replace:
    path: /tmp/ctl/scripts/createdb.sh
    regexp: '^ROOTPASS=""$'
    replace: "ROOTPASS=root"
  no_log: true

- name: hack for mysql conn
  ansible.builtin.replace:
    path: /tmp/ctl/scripts/createdb.sh
    regexp: '^mysql <<MYSQL_SCRIPT$'
    replace: "mysql --password=root <<MYSQL_SCRIPT"
  no_log: true

- name: Run the Trillian database creation script
  ansible.builtin.shell:
    cmd: /tmp/ctl/scripts/createdb.sh
    chdir: /tmp/ctl/scripts
  become: true

- name: Run MariaDB daemon
  ansible.builtin.systemd:
    name: mariadb
    state: started

# Build and configure Trillian
- name: Clone the Trillian public repository
  ansible.builtin.git:
    repo: https://github.com/google/trillian
    dest: /tmp/trillian
    force: yes

- name: Change the mysql provider configuration to match credentials set via ansible
  ansible.builtin.replace:
    path: /tmp/trillian/storage/mysql/provider.go
    regexp: "\"test:zaphod.+?['\"]"
    replace: "\"{{ trillian_db_user }}:{{ trillian_db_password }}@tcp(127.0.0.1:3306)/{{ trillian_db_name }}\""

- name: Build the Trillian log server
  ansible.builtin.shell:
    cmd: "go build"
    chdir: /tmp/trillian/cmd/trillian_log_server

- name: Move the Trillian log server binary into /usr/local/bin
  ansible.builtin.copy:
    remote_src: yes
    src: /tmp/trillian/cmd/trillian_log_server/trillian_log_server
    dest: /usr/local/bin/
    mode: u=rwx,g=rx,o=x
  become: true

- name: Create the trillian log server systemd unit
  ansible.builtin.template:
    src: "{{ role_path }}/templates/trillian-log-server.j2"
    dest: /etc/systemd/system/trillian_log_server.service
  become: true

- name: Build the Trillian log signer
  ansible.builtin.shell:
    cmd: go build
    chdir: /tmp/trillian/cmd/trillian_log_signer

- name: Move the Trillian log signer binary into /usr/local/bin
  ansible.builtin.copy:
    remote_src: yes
    src: /tmp/trillian/cmd/trillian_log_signer/trillian_log_signer
    dest: /usr/local/bin/
    mode: u=rwx,g=rx,o=x
  become: true

- name: Build the Trillian createtree binary
  ansible.builtin.shell:
    cmd: go build
    chdir: /tmp/trillian/cmd/createtree

- name: Move the Trillian createtree binary into /usr/local/bin
  ansible.builtin.copy:
    remote_src: yes
    src: /tmp/trillian/cmd/createtree/createtree
    dest: /usr/local/bin/
    mode: u=rwx,g=rx,o=x
  become: true

- name: Create the Trillian log signer systemd unit
  ansible.builtin.template:
    src: "{{ role_path }}/templates/trillian-log-signer.j2"
    dest: /etc/systemd/system/trillian_log_signer.service
  become: true

- name: Run the Trillian log signer
  ansible.builtin.systemd:
    name: trillian_log_signer
    state: started
    daemon_reload: yes
  become: true

- name: Run the Trillian log server
  ansible.builtin.systemd:
    name: trillian_log_server
    state: started
    daemon_reload: yes
  become: true

# CTFE server
- name: Install CTFE server
  ansible.builtin.shell:
    cmd: go install github.com/google/certificate-transparency-go/trillian/ctfe/ct_server@latest
  environment:
    GOPATH: /tmp/ctl

- name: Move ct_server binary to /usr/local/bin
  ansible.builtin.copy:
    remote_src: yes
    src: /tmp/ctl/bin/ct_server
    dest: /usr/local/bin/
    mode: u=rwx,g=rx,o=x
  become: true

# Create a private key
- name: Generate key
  ansible.builtin.shell:
    cmd: openssl ecparam -genkey -name prime256v1 -noout -out unenc.key
    chdir: /tmp/ctl/

- name: Encrypt private key
  ansible.builtin.expect:
    command: openssl ec -in unenc.key -out privkey.pem -des3
    responses:
      'Enter pass phrase for PEM': '{{ private_key_password }}'
      'Verifying - Enter pass phrase for PEM': '{{ private_key_password }}'
    chdir: /tmp/ctl/

- name: Remove the unencrypted key
  ansible.builtin.file:
    path: /tmp/ctl/unenc.key
    state: absent

# Create a Tree ID
- name: Create a Tree ID
  ansible.builtin.shell:
    cmd: createtree --admin_server localhost:8091
  register: createtree_output

- name: Register Tree ID
  ansible.builtin.set_fact:
    log_id: "{{ createtree_output.stdout }}"
    cacheable: true

# Copy local fulcio-root.pem certificate to host
- name: Copy Fulcio CA certificate to host
  ansible.builtin.copy:
    src: ~/sigstore-fulcio/fulcio-root.pem
    dest: /etc/ctfe-config/fulcio-root.pem
  become: true

# Move the private key to /etc/ctfe-config
- name: Move the private key to /etc/ctfe-config
  ansible.builtin.copy:
    remote_src: yes
    src: /tmp/ctl/privkey.pem
    dest: /etc/ctfe-config
  become: true

# Set up the config file
- name: Set up the CTL config file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/ct_cfg.j2"
    dest: /etc/ctfe-config/
  become: true