---
# vars file for provision-ec2

region: "eu-west-1"

# VPC
vpc_name: "sthw-ansible-demo-vpc"
vpc_cidr: 172.31.0.0/16

# Subnet
subnet_name: "sthw-ansible-demo-subnet"
subnet_cidr: 172.31.50.0/24

# Security group
security_group_name: "sthw-ansible-demo-sg"
 
# Local path to save EC2 keypair
ec2_key_directory: "/home/vagrant/sthw-demo/keys/"
keypair_name: "ec2_key_pair"

# Instance to tag with name
instances_to_tag:
  - name: "sigstore-rekor"
  - name: "sigstore-fulcio"
  - name: "sigstore-oauth2"
  - name: "sigstore-ctl"

# Instance that need a public IP allocated
instances_public_ip:
  - name: "sigstore-rekor"
  - name: "sigstore-fulcio"
  - name: "sigstore-oauth2"
